### ISSUE TITLE
SeeAlsoのURLミス

### ISSUE THREAD

**Issue by kninomiya-mope** [aidrd/nando#13]
肺動脈性肺高血圧症
SeeAlso:httpss://www.nanbyou.or.jp/entry/3934
と、httpsよりsecureっぽそうなURLミスを複数発見。

**Comment by roy29fuku** [comment]
httpss問題は大元のファイルからそうなってますね。
https://github.com/precemia/nando_originalData/blob/master/nanbyo.json#L551

@precemia 仁宮さんマターですね。
修正お願いします〜

**Comment by kninomiya-mope** [comment]
ベータ版以降でいいと思います。
SeeAlsoはたしか藤原さんにお願いしてやってもらったような気がしています。
@fujitoyo 
単純なミスであればいいんですが、なにかが潜んでいると怖いので落ち着いたら確認させてください〜

**Comment by fujitoyo** [comment]
@precemia 
パートさんに作ってもらった元ファイルが間違っていました．
そして，全てのリンクをクリックして確認したはずですが，なんとhttpssでも，Excelが修正してhttpsに飛ばしてくれていました！
ありがた迷惑〜

**Comment by fujitoyo** [comment]
@precemia 
全てのリンクは確認済みなので，単純にjsonファイルのhttpssをhttpsに変換してもらえれば大丈夫です．

**Comment by kninomiya-mope** [comment]
@fujitoyo 了解です！

**Comment by roy29fuku** [comment]
@precemia 
Github更新したら教えてください〜

**Comment by kninomiya-mope** [comment]
jsonデータ修正しました
