### ISSUE TITLE
isDefinedByのURLが変更される可能性

### ISSUE THREAD

**Issue by kninomiya-mope** [aidrd/nando#14]
以前isDefinedByで定義した調査票のURLが変更されたことがあるので、間にリダイレクトできるようなページをかませたほうがいいのではないか。

**Comment by roy29fuku** [comment]
これの対応はベータ版以降ですかね

**Comment by fujitoyo** [comment]
プロパティを
isDefinedBy
から
dcterms:source
に変更済み
