### ISSUE TITLE
Descripionを設置する

### ISSUE THREAD

**Issue by kninomiya-mope** [aidrd/nando#15]
指定難病に関して、疾患のDescriptionとして公文書が権利関係含め問題なく使用できるということを確認済み。したがって、追加しても構わないのではないか。
小児慢性特定疾病に関しては小満情報センターとなってしまうか、うまく公文書が見つかれば使用したい。

**Comment by fujitoyo** [comment]
厚労省のHPから全指定難病の「概要、診断基準等」ワードファイルを自動取得し，ファイル内の概要を自動抽出するスクリプトを作成
nando/data_summary/get_summary_from_mhlw.sh

以下に全指定難病の概要が収納される
nando/data_summary/mhlw_実施日付/1_333.num.summary.tsv

パートさんがバグを確認中

**Comment by fujitoyo** [comment]
パートさんがdifff.jpを利用して，ワードファイルの概要とプログラムで自動抽出した内容を比較しましたが，問題なく自動抽出できていました．

nando/data_summary/mhlw_実施日付/1_333.num.summary.tsv
を元のjsonファイルに組み込んでもらえますか？

NANDO ver0.3には，疾患概要も含めることができればと思います．

**Comment by kninomiya-mope** [comment]
jsonファイルは修正しました。ttlで適切に変換できるように修正していただければと思います
