### ISSUE TITLE
疾患説明の日本語ソースをSeeAlsoの追加

### ISSUE THREAD

**Issue by kninomiya-mope** [aidrd/nando#20]
Genereviews日本語版やUR-DBMSなどの日本語リソースなどもseealsoとして追加できてもいいのかも知れない。（長期的話）

**Comment by fujitoyo** [comment]
GeneReviews/GeneReviews日本語版，UR-DBMSはOMIMと紐づいているので，MONDOと対応付けば追加可能です．

**Comment by fujitoyo** [comment]
UR-DBMS，KEGGについては対応済
そのほかについては，ROIS-DS-JOINT2021の枠組みで検討
