### ISSUE TITLE
MONDO mapping時のabbreviation問題

### ISSUE THREAD

**Issue by kninomiya-mope** [aidrd/nando#23]
（簡単には解決できない問題ですが、忘れないように記録しておきます）
疾患によってはまったく同じabbreviationを持つ場合があり、誤って別の疾患（特にcommon diseaseであることが経験的に多い気がする）と対応付けられてしまうことがある。
文字列上の小さなゆらぎで当たらない場合でも、Abbreviationのおかげでピッタリ当てはまることもあるため、mapping時に単純に除外することは適切ではない。そのあたりのfalse positiveへの対応を考える必要がある。

（参考）　http://allie.dbcls.jp

**Comment by fujitoyo** [comment]
一度はマッピング結果を目視で確認する必要があると思います．
メンバーで手分けすれば，どうにかなる数だと思います．
以降のアップデートでは，差分のみを確認すれば良いと思います．

**Comment by kninomiya-mope** [comment]
たしかにです。
一人では決してできなかった仕事ですね。（感慨）

**Comment by fujitoyo** [comment]
前処理後の疾患名で，6文字以下でマッチしたものについては，全て目視で確認（ダブルチェック）
