### ISSUE TITLE
turtle上の変更・追加

### ISSUE THREAD

**Issue by kninomiya-mope** [aidrd/nando#30]
- 指定難病等の補助対象外だが情報リソースに書かれている場合はオントロジーに入れて、補助対象外とかくため、あるいは他の備考を記載するためにコメント部分はturtleにrdf:comment（のようなもの）を入れる。また、turtleには指定の対象外であるかをbooleanで示せるような新たなpropertyを導入を検討する。
- 「概念同士の一致は含まれる疾患まで一致しているという前提を置くと、大分類・中分類・疾患分類においては一致していないので対応させないが、各疾患項目であれば一致するので対応付ける。」という論理になるが、後者は必ずしも正しいわけではなく、概念同士の一致の意味を使い分けるよりも、シンプルに全て文字列でマッチングさせたという方が簡単に説明できるので採用する。マッチングに関してはあくまでも機械的につけたが、概念的に外れる可能性があるということは書いた上で書いて、プログラム上でも大分類・中分類もマッチングするようにする。
- ” and” ” and “やGreek, Roman numberなど文字列マッチングプログラムなどを改善
- 「５文字までの英語はすべてNANDOーMONDOマッチング時に除去」という統一ルールで処理する可能性がある

**Comment by fujitoyo** [comment]
本Issueの内容を#31〜#36に分割したので，本Issueはクローズする．
