### ISSUE TITLE
NANDOtoMONDO マッピング：Exact SynonymsとRelated Synonyms

### ISSUE THREAD

**Issue by fujitoyo** [aidrd/nando#51]
マッピングするシノニムはExact SynonymsとRelated Synonymsの両方？

NANDO
https://nanbyodata.jp/disease/NANDO:1200867
MONDO
https://monarchinitiative.org/disease/MONDO:0054698

上記のNANDOとMONDOは何と何が紐付いているのか？

**Comment by kninomiya-mope** [comment]
現状のコードではどこまで参照するかを切り替えられるようになっていますが、そのあたりは最終的には検討したほうがいい課題ですよね。今どうなっていたかは忘れてしまいましたが。

**Comment by fujitoyo** [comment]
ラベルとEXACT Synonymはマッピング対象として採用
RELATED, NARROW, BROAD Synonymでのマッピングは，ラベルとEXACT SynonymでマッピングされなかったNANDO-MONDOペアについてのみ採用
